language: python
cache: pip
python:
  - "2.6"
  - "2.7"

before_script:
  - pip install -r requirements/test.txt
  - echo $TEST
script:
  - nosetests --with-coverage --cover-branches --cover-package pyg
after_success:
  - coveralls
